name: Update TryHackMe badge

on:
  push:
    paths:
      - README.md
      - .github/workflows/update-thm-badge.yml
  schedule:
    - cron: '0 */6 * * *'   # de 6 em 6 horas
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-thm-badge
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Descarregar badge
        run: |
          curl -fsSL "https://tryhackme-badges.s3.amazonaws.com/Somat27.png?cache-control=no-cache" -o thm_badge.png

      - name: Commit se mudou
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Comita quer seja novo (??) quer tenha mudado (M)
          if [[ -n "$(git status --porcelain=1 -- thm_badge.png)" ]]; then
            git add thm_badge.png
            git commit -m "chore: update THM badge"
            git push
          else
            echo "Sem alterações"
          fi
