name: Update TryHackMe badge
on:
  schedule:
    - cron: '0 */6 * * *'   # de 6 em 6 horas (ajusta se quiseres)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Descarregar badge
        run: |
          curl -sL "https://tryhackme-badges.s3.amazonaws.com/Somat27.png?cache-control=no-cache" -o thm_badge.png
      - name: Commit se mudou
        run: |
          if ! git diff --quiet -- thm_badge.png; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add thm_badge.png
            git commit -m "chore: update THM badge"
            git push
          else
            echo "Sem alterações"
          fi
